
<div class="container" style="position: relative; top: 50px;">

	<h1>Data Charts of call back</h1>
	
	<div id='canvasDiv' style="width: 100%; height: 100%">
	</div>
	Upload batch range/check time range:<input type='text' class='datetimepicker' id='startDate'
		value='' placeholder='startDate' />-<input type='text'
		class='datetimepicker' id='endDate' value='' placeholder='endDate' />
	<button class='btn-xs' onclick='return Charts.batchOverview();'>Batch overview</button>
	<button class='btn-xs' onclick='return Charts.showHarass();'>Harass Rate</button>
	<button class='btn-xs' onclick='return Charts.resetCanvas();'>Clear Charts</button>

</div>
<!-- /container -->
<?php
echo $this->tag->javascriptInclude ( 'js/moment.min.js' );
echo $this->tag->javascriptInclude ( 'js/charts.js?t=0525' );
?>
