
<div class="container" style="position: relative; top: 50px;">

	<h1>OSV overview</h1>
	
	<div id='canvasDiv' style="width: 100%; height: 100%">
	</div>
	Check time:<input type='text' class='datetimepicker' id='startDate'
		value='' placeholder='startDate' />-<input type='text'
		class='datetimepicker' id='endDate' value='' placeholder='endDate' />
	<button class='btn-xs' onclick='return Charts.cntRecording();'>Show/refresh cntRecording</button>
	<button class='btn-xs' onclick='return Charts.recDuration();'>Show/refresh recDuration</button>
	<button class='btn-xs' onclick='return Charts.resetCanvas();'>Clear Charts</button>
	<!--$this->tag->linkTo(['charts/signin', 'SignIn', 'class' => 'btn btn-default','target'=>'_blank']) -->

</div>
<!-- /container -->
<?php
echo $this->tag->javascriptInclude ( 'js/charts.js?t=0525' );
?>