
<div class="container" style="position: relative; top: 50px;">

	<h1>DingCheck overview</h1>
	
	<div id='canvasDiv' style="width: 100%; height: 100%">
	</div>
	Visit Date:<input type='text' class='datepicker' id='startDate'
		value='' placeholder='startDate' />-<input type='text'
		class='datepicker' id='endDate' value='' placeholder='endDate' />
	<button class='btn-xs' onclick='return Charts.visitOverview();'>Show/refresh visit overview</button>
	<button class='btn-xs' onclick='return Charts.avgSecCost();'>Show/refresh checking avgSecCost</button>
	<button class='btn-xs' onclick='return Charts.resetCanvas();'>Clear Charts</button>
	<!--$this->tag->linkTo(['charts/signin', 'SignIn', 'class' => 'btn btn-default','target'=>'_blank']) -->

</div>
<!-- /container -->
<?php
echo $this->tag->javascriptInclude ( 'js/charts.js?t=0524' );
?>