<h2>Sign in here</h2>

<?php echo $this->tag->form("#"); ?>

<p>
	<label for="name">Name</label>
        <?php echo $this->tag->textField(["name","class"=>"form-control input-xs","max-length"=>10]); ?>
    </p>

<p>
	<label for="email">E-Mail</label>
        <?php echo $this->tag->textField(["email","class"=>"form-control input-xs","max-length"=>10]); ?>
    </p>

<p>
        <?php								
echo $this->tag->tagHtml ( "input",[ 
										"value"=>"Sign-in",
										"type"=>"button",
										"class" => "btn btn-default",
										"onclick"=>"return SignIn.login();"								
								] )
								?>        
    </p>

</form>

<?php echo $this->tag->javascriptInclude('js/signup.js');
?>